---
schema:
  procedures: {}
  tables:
    account_types:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - account_type_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - last_update_user
          match_type: ''
          name: account_types_fk_last_update_user
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - account_id
          reference_table: accounts
          type: FOREIGN KEY
      fields:
        account_type_id:
          data_type: 1
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: account_type_id
          order: 1
          size:
            - 0
        description:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: description
          order: 2
          size:
            - 0
        last_update_time:
          data_type: timestamp with time zone
          default_value: !!perl/ref
            =: now()
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_update_time
          order: 4
          size:
            - 0
        last_update_user:
          data_type: int
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_update_user
          order: 3
          size:
            - 0
      indices:
        - fields:
            - last_update_user
          name: account_types_idx_last_update_user
          options: []
          type: NORMAL
      name: account_types
      options: []
      order: 3
    accounts:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - account_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - account_type_id
          match_type: ''
          name: accounts_fk_account_type_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - account_type_id
          reference_table: account_types
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - contact_title_id
          match_type: ''
          name: accounts_fk_contact_title_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - title_id
          reference_table: contact_titles
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - country_id
          match_type: ''
          name: accounts_fk_country_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - country_id
          reference_table: countries
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - last_update_user
          match_type: ''
          name: accounts_fk_last_update_user
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - account_id
          reference_table: accounts
          type: FOREIGN KEY
      fields:
        account_id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: account_id
          order: 1
          size:
            - 0
        account_name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: account_name
          order: 5
          size:
            - 0
        account_type_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: account_type_id
          order: 6
          size:
            - 0
        alt_account_id_1:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: alt_account_id_1
          order: 2
          size:
            - 0
        alt_account_id_2:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: alt_account_id_2
          order: 3
          size:
            - 0
        city:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: city
          order: 10
          size:
            - 0
        contact_job_title:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: contact_job_title
          order: 15
          size:
            - 0
        contact_name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: contact_name
          order: 7
          size:
            - 0
        contact_number:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: contact_number
          order: 16
          size:
            - 0
        contact_title_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: contact_title_id
          order: 14
          size:
            - 0
        country_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: country_id
          order: 13
          size:
            - 0
        county:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: county
          order: 11
          size:
            - 0
        email_address:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: email_address
          order: 19
          size:
            - 0
        fax_number:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: fax_number
          order: 18
          size:
            - 0
        last_update_date:
          data_type: timestamp with time zone
          default_value: !!perl/ref
            =: now()
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_update_date
          order: 20
          size:
            - 0
        last_update_user:
          data_type: int
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_update_user
          order: 21
          size:
            - 0
        legacy_account_id:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: legacy_account_id
          order: 4
          size:
            - 0
        mobile_number:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: mobile_number
          order: 17
          size:
            - 0
        postcode:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: postcode
          order: 12
          size:
            - 0
        street_1:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: street_1
          order: 8
          size:
            - 0
        street_2:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: street_2
          order: 9
          size:
            - 0
      indices:
        - fields:
            - account_type_id
          name: accounts_idx_account_type_id
          options: []
          type: NORMAL
        - fields:
            - contact_title_id
          name: accounts_idx_contact_title_id
          options: []
          type: NORMAL
        - fields:
            - country_id
          name: accounts_idx_country_id
          options: []
          type: NORMAL
        - fields:
            - last_update_user
          name: accounts_idx_last_update_user
          options: []
          type: NORMAL
      name: accounts
      options: []
      order: 6
    contact_titles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - title_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        description:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: description
          order: 2
          size:
            - 0
        title_id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: title_id
          order: 1
          size:
            - 0
      indices: []
      name: contact_titles
      options: []
      order: 1
    countries:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - country_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - language_id
          match_type: ''
          name: countries_fk_language_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - language_id
          reference_table: languages
          type: FOREIGN KEY
      fields:
        country_code:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: country_code
          order: 2
          size:
            - 3
        country_id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: country_id
          order: 1
          size:
            - 0
        country_name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: country_name
          order: 3
          size:
            - 0
        language_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: language_id
          order: 4
          size:
            - 0
      indices:
        - fields:
            - language_id
          name: countries_idx_language_id
          options: []
          type: NORMAL
      name: countries
      options: []
      order: 4
    languages:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - language_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - language_code
          match_type: ''
          name: languages_language_code
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        language_code:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: language_code
          order: 2
          size:
            - 2
        language_id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: language_id
          order: 1
          size:
            - 0
        language_name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: language_name
          order: 3
          size:
            - 0
      indices: []
      name: languages
      options: []
      order: 2
    translations:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - language_id
          match_type: ''
          name: translations_fk_language_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - language_id
          reference_table: languages
          type: FOREIGN KEY
      fields:
        area:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: area
          order: 1
          size:
            - 0
        language_id:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: language_id
          order: 4
          size:
            - 0
        literal:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: literal
          order: 3
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 0
      indices:
        - fields:
            - language_id
          name: translations_idx_language_id
          options: []
          type: NORMAL
      name: translations
      options: []
      order: 5
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Country
      - Account
      - ContactTitle
      - AccountType
      - Language
      - Translation
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11018
