package SAMS::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SAMS::Schema',
    connect_info => ['dbi:Pg:dbname=mikef-sams-2', 'mikef', { pg_enable_utf8  => 1 } ],
);

=head1 NAME

SAMS::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SAMS>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SAMS::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Mike Francis

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
